config/routes.rb
CopyProcess::Application.routes.draw do

  devise_for :users, :skip => [:registrations] do
    get "/login" => "devise/sessions#new", :as => :login
    post '/login' => "devise/sessions#create"
    get "/logout" => "devise/sessions#destroy", :as => :logout
  end

  resources :sites do
    resources :documents, except: :index
    resources :element_types, :only => [:index, :show, :destroy, :edit, :update]
    resources :elements, :only => [:index]
    resource :search_and_replace, :only => [:new, :create], :controller => 'search_and_replace'
  end
  
  resources :versions, only: :show do
    resources :notes, :except => [:show, :new, :edit]
  end
  
  
  resources :documents do
    resources :versions, only: :create
  end
  
  root :to => 'sites#index'
  
  match '/compile_documents/:id' => 'sites#compile_documents', :as => :compile_documents, :via => :post
end

app/controllers/element_types_controller.rb
class ElementTypesController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @site = Site.find(params[:site_id])
    @element_types = ElementType.where(:site_id => @site.id).order(:name)
  end
  
  def show
    @site = Site.find(params[:site_id])
    @element_type = ElementType.find(params[:id])
  end
  
  def destroy
    @site = Site.find(params[:site_id])
    @element_type = ElementType.find(params[:id])
    @element_type.destroy
    redirect_to site_element_types_url(@site)
  end
  
  def edit
    @site = Site.find(params[:site_id])
    @element_type = ElementType.find(params[:id])
  end
  
  def update
    @site = Site.find(params[:site_id])
    @element_type = ElementType.find(params[:id])
    if @element_type.update_attributes(params[:element_type])
      redirect_to [@site, @element_type], :notice => 'Element type updated successfully!'
    else
      render :action => 'edit'
    end
  end
end

app/helpers/element_types_helper.rb
module ElementTypesHelper
  
  def show_element_content(element_types, site)
    loop_through_elements(element_types, 'table') do |output, last|
      element_types.each do |ele|
        if last != get_element_type_name(ele.name)
          last = get_element_type_name(ele.name)
          output << "</table></div><h3><a href=\"#\">#{last}</a></h3><div><table>"
        end
        output << "<tr><td>#{link_to(get_element_content(ele.name), site_element_type_path(site, ele.id))}</td>" + 
          "<td>#{link_to('Edit', edit_site_element_type_path(site, ele.id))}</td></tr>"
      end
    end
  end
  
  def loop_through_elements(element_types, tag = 'ul', &block)
    last = get_element_type_name(element_types.first.name)
    output = "<h3><a href=\"#\">#{last}</a></h3><div><#{tag}>"
    if last.nil?
      raise "ElementReturnedNullException - this shouldn't happen."
    else
      yield(output, last)
      output << "</#{tag}></div>"
    end
    output.html_safe
  end
  
  def list_elements(element_types)
    loop_through_elements(element_types) do |output, last|
      element_types.each do |ele|
        if last != get_element_type_name(ele.name)
          last = get_element_type_name(ele.name)
          output << "</ul></div><h3><a href=\"#\">#{last}</a></h3><div><ul>"
        end
        output << "<li>#{get_element_content(ele.name)}<ul>"
        ele.elements.each do |element|
          output << "<li>#{h(element.content)}</li>"
        end
        output << "</ul>"
      end
    end
  end
  
  def get_element_type_name(ele)
    ele.split(" ")[0]
  end
  
  def get_element_content(ele)
    words = ele.split(" ")
    words[1..words.size].join(" ")
  end
end

app/views/element_types/edit.html.haml
%h1= "Editing #{@element_type.name}"

= form_for([@site, @element_type]) do |f|
  - if @element_type.errors.any?
    #error_explanation
      %h2= pluralize(@element_type.errors.count, 'error') |
      prohibited this document from being saved:
      
      %ul
      - @element_type.errors.full_messages.each do |msg|
        %li= msg
        
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit

app/views/element_types/index.html.haml
- content_for(:head) do
  = stylesheet_link_tag 'jquery-ui-1.8.15.custom.css'
  = javascript_include_tag 'jquery-ui-1.8.15.custom.min.js'
  = javascript_include_tag 'element_types.js.coffee'
%h1 Listing Element Types

%p= link_to "View all elements at once", site_elements_path(@site)

#accordion
  =show_element_content(@element_types, @site)
  
%p= link_to 'Back', site_path(@site)

app/views/element_types/show.html.haml
%h1= @element_type.name

%p= link_to 'Edit', edit_site_element_type_path(@site, @element_type)

%p Elements:
%ul
  - @element_type.elements.each do |ele|
    %li= ele.content
  
%p= link_to 'Delete this element type', site_element_type_path(@site, @element_type), :method => :delete, :confirm => 'Are you sure?'
%p
  = link_to 'Back to element types', site_element_types_path(@site)
  = link_to 'Back to site', site_path(@site)