config/routes.rb
CopyProcess::Application.routes.draw do

  devise_for :users, :skip => [:registrations] do
    get "/login" => "devise/sessions#new", :as => :login
    post '/login' => "devise/sessions#create"
    get "/logout" => "devise/sessions#destroy", :as => :logout
  end

  resources :sites do
    resources :documents, except: :index
    resources :element_types, :only => [:index, :show, :destroy, :edit, :update]
    resources :elements, :only => [:index]
    resource :search_and_replace, :only => [:new, :create], :controller => 'search_and_replace'
  end
  
  resources :versions, only: :show do
    resources :notes, :except => [:show, :new, :edit]
  end
  
  
  resources :documents do
    resources :versions, only: :create
  end
  
  root :to => 'sites#index'
  
  match '/compile_documents/:id' => 'sites#compile_documents', :as => :compile_documents, :via => :post
end

app/models/document.rb
class Document < ActiveRecord::Base
  include CopyProcess

  belongs_to :site
  has_many :versions, before_add: :set_version_parent
  belongs_to :active_version, class_name: "Version", foreign_key: "active_version_id"
  
  accepts_nested_attributes_for :versions

  validates_associated :versions, :active_version
  # validates_presence_of :active_version
  
  # validate :document_is_in_valid_format
  # validates :content, :presence => true
  
  before_create :set_active_version
  before_save :remove_windows_lines
  
  def name
    # self.active_version.name
    if content.blank?
      'Document'
    else
      content.split(/\n/)[1..3].join(' - ').gsub(/\/\*|\\\*/,'')
    end
  end
  
  def value
    if self.content.blank?
      "/*\nType: \nLayer: \nVariation: \n*/"
    else
      self.content
    end
  end
  
  def active_version_object
    self.active_version || self.versions.first
  end
  
  def content
    self.active_version_object.content
  end
  
  private
  
  def remove_windows_lines
    self.content = self.content.gsub(/\r\n/, "\n")
  end
  
  def set_active_version
    self.active_version = self.versions.first
  end
  
  def set_version_parent(child)
    child.document ||= self
  end
  
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :authenticate_user!
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
    @site = Site.find(params[:site_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])
    @site = Site.find(params[:site_id])
    
    if params[:version_id]
      @version = Version.find(params[:version_id])
    else
      @version = @document.active_version
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new
    @version = Version.new
    @document.active_version = @version
    @document.versions << @version
    @site = Site.find(params[:site_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
    @site = Site.find(params[:site_id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @site = Site.find(params[:site_id])
    @document = @site.documents.build
    @version = @document.versions.build(params[:document][:active_version])
    @document.active_version = @version
    respond_to do |format|
      if @site.save
        format.html { redirect_to site_url(@site), :notice => 'Document was successfully created.' }
        format.json { render :json => @document, :status => :created, :location => @document }
      else
        format.html { render :action => "new" }
        format.json { render :json => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])
    @site = Site.find(params[:site_id])
    respond_to do |format|
      if @document.active_version.update_attributes(params[:document][:active_version])
        format.html { redirect_to site_url(@site), :notice => 'Document was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    @site = Site.find(params[:site_id])

    respond_to do |format|
      format.html { redirect_to @site }
      format.json { head :ok }
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def content_with_notes(version)
    content = h(version.content)
    offset = 0
    
    notes = []
    Rails.logger.debug("Content h'd: #{content[0..20]}")
    
    version.notes.each do |note|
      tag = "<span class=\"to_change\" id=\"sel_#{note.id}\">"
      close_tag = '</span>'
      
      content.insert(note.start_character + offset, tag)
      offset += tag.size
      content.insert(note.end_character + offset, close_tag)
      offset += close_tag.size
    end
    
    Rails.logger.debug("Content final: #{content[0..20]}")
    
    content.html_safe
  end
  
end

app/views/documents/_form.html.haml
= form_for([@site, @document]) do |f|
  - if @document.errors.any?
    #error_explanation
      %h2= pluralize(@document.errors.count, "error") |
      prohibited this document from being saved:

      %ul
      - @document.errors.full_messages.each do |msg|
        %li= msg
  
  = f.fields_for :active_version do |builder|
    .area_container
      .field
        = builder.label :content 
        = builder.text_area :content , :cols => 90, :rows => 40, :value => @document.value
      .tips
        %h3 Always consider the following:
        %ul
          %li The combination of the Type/Layer/City at the top must be unique
          %li The Type/Layer/City values are case sensitive. Please keep to your own conventions
          %li 
            Any sentences you dont want split (think title tags), add an * to the end of ? ! . as you need to. You
            can use the Delimit sentences button to do this easily.
          %li For asterisks you actually need in the copy that follow ? ! ., simply double it up. (.**)
          %li Can easily convert lines of text to a bullet list by selecting and clicking the button below.
  .actions
    = f.submit
    
  
%p
  %input{ :id => 'listify', :value => 'Listify Text', :type => 'button'  }
  %input{ :id => 'add_asterisks', :value => "Delimit Sentences", :type => 'button'}

app/views/documents/edit.html.haml
%h1 Editing document

= render 'form'

= link_to 'Back', site_path(@site)

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <tr>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @documents.each do |document| %>
  <tr>
    <td><%= document.content %></td>
    <td><%= link_to 'Show', site_document_path(@site, document) %></td>
    <td><%= link_to 'Edit', edit_site_document_path(@site, document) %></td>
    <td><%= link_to 'Destroy', site_document_path(@site, document), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document', new_site_document_path(@site) %>

app/views/documents/new.html.haml
%h1 New document

%p
  %strong Read first: 
  Each document requires 5 lines at the top, to identify what it is about. For example:
  
="<pre>\n/*\nType: Lawn Care\nLayer: State\nVariation: 1\n*/</pre>".html_safe
%p
  Simply increase the variation number for each "Lawn Care" document at the "State layer"

= render 'form'

= link_to 'Back', site_path(@site)

app/views/documents/show.html.haml
:javascript
  window['version-id'] = "#{@version.id}";
%p#notice= notice

.view
  %p 
    Version: 
    %br
    %select#select-version
      - @document.versions.each_with_index do |v, i|
        - if v.id == @version.id
          %option{ value: "#{v.id}", selected: "selected" }= i + 1
        - else
          %option{ value: "#{v.id}" }= i + 1
        
  %p
    %b Content:
    %pre= content_with_notes(@version)

= link_to 'Edit', edit_site_document_path(@site, @document) 
|
= link_to 'Back', site_path(@site)