config/routes.rb
CopyProcess::Application.routes.draw do

  devise_for :users, :skip => [:registrations] do
    get "/login" => "devise/sessions#new", :as => :login
    post '/login' => "devise/sessions#create"
    get "/logout" => "devise/sessions#destroy", :as => :logout
  end

  resources :sites do
    resources :documents, except: :index
    resources :element_types, :only => [:index, :show, :destroy, :edit, :update]
    resources :elements, :only => [:index]
    resource :search_and_replace, :only => [:new, :create], :controller => 'search_and_replace'
  end
  
  resources :versions, only: :show do
    resources :notes, :except => [:show, :new, :edit]
  end
  
  
  resources :documents do
    resources :versions, only: :create
  end
  
  root :to => 'sites#index'
  
  match '/compile_documents/:id' => 'sites#compile_documents', :as => :compile_documents, :via => :post
end

app/controllers/search_and_replace_controller.rb
class SearchAndReplaceController < ApplicationController
  before_filter :authenticate_user!
  def new
    @site = Site.find(params[:site_id])
  end
  
  def create
    @site = Site.find(params[:site_id])
    if params[:search].blank?
      nothing_found(@site.id)
    else
      @element_results = Element.search_by_content(@site.id, params)
      if @element_results.size == 0
        nothing_found(@site.id)
      elsif !params[:replace].blank?
        case_sensitive = (params[:case_sensitive] == "1")
        @element_results.each do |ele|
          if case_sensitive
            ele.update_attribute(:content, ele.content.gsub("#{params[:search]}", params[:replace]))
          else
            ele.update_attribute(:content, ele.content.gsub(/#{regex_safe(params[:search])}/i, params[:replace]))
          end
        end
      end
    end
  end
  
  private
  
  def nothing_found(site)
    redirect_to new_site_search_and_replace_url(site), :notice => 'Content not found.'
  end
  
  def regex_safe(str)
    str.gsub(/\W+/) { |match| "\\#{match}" }
  end
end

app/helpers/search_and_replace_helper.rb
module SearchAndReplaceHelper
end

app/views/search_and_replace/create.html.haml
%h1 Content found:

= link_to 'Search again', new_site_search_and_replace_path(@site)

%table
  %tr
    %th Type Name
    %th Content
  - @element_results.each do |element|
    %tr
      %td.etname= element.element_type_name
      %td= element.content

app/views/search_and_replace/new.html.haml
%h1 Search & replace
%p#error= notice
%p 
  Use the form to search for content. If you wish, you can replace that content as well. Leave the replace box empty if you
  just wish to search.

= form_tag site_search_and_replace_path(@site) do 
  .field
    = label_tag :search, 'Search: '
    = text_field_tag :search
  .field
    = label_tag :replace, 'Replace with: '
    = text_field_tag :replace
  .field
    = label_tag :case_sensitive, 'Case sensitive: '
    = check_box_tag :case_sensitive
  .actions
    = submit_tag 'Search'