config/routes.rb
CopyProcess::Application.routes.draw do

  devise_for :users, :skip => [:registrations] do
    get "/login" => "devise/sessions#new", :as => :login
    post '/login' => "devise/sessions#create"
    get "/logout" => "devise/sessions#destroy", :as => :logout
  end

  resources :sites do
    resources :documents, except: :index
    resources :element_types, :only => [:index, :show, :destroy, :edit, :update]
    resources :elements, :only => [:index]
    resource :search_and_replace, :only => [:new, :create], :controller => 'search_and_replace'
  end
  
  resources :versions, only: :show do
    resources :notes, :except => [:show, :new, :edit]
  end
  
  
  resources :documents do
    resources :versions, only: :create
  end
  
  root :to => 'sites#index'
  
  match '/compile_documents/:id' => 'sites#compile_documents', :as => :compile_documents, :via => :post
end

app/models/site.rb
class Site < ActiveRecord::Base
  include CopyProcess
  
  default_scope order: "name"
  
  validates :name, :presence => true
  has_many :documents, :dependent => :destroy
  has_many :element_types, :dependent => :destroy
  
  def to_csv(with_parents, encode)
    p = CopyProcess::Processor.new
    p.compile_files_to_csv(self, with_parents, encode)
  end
  
  def compile_to_save(params)
    # Destroy all existing
    destroy_all_element_types

    set_documents(params[:include]) unless params[:include].nil?

    # build new
    files = []
    p = prepare_documents(files)
    p.compile_files_to_element_types(files, self)
  end
  
  def tokens
    tokens_to_hash(scan_elements(/\[[a-zA-Z\s]+\]/))
  end
  
  def destroy_all_element_types
    self.element_types.destroy_all
  end

  def scan_elements(regex)
    content = ''
    self.element_types.each do |et|
      content << et.all_content
    end
    content.scan(regex)
  end
  
  def active_tokens
    tokens_to_hash(scan_elements(/\$\{[a-zA-Z]+\.[a-zA-Z]+\}/))
  end
  
  def documents_by_name
    docs = {}
    documents.each do |d|
      docs[d.name] = d
    end
    docs.sort{ |a, b| a[0]<=>b[0] }
  end
  
  private

  def set_documents(include_ids)
    ids = []
    include_ids.each do |k, v|
      if v == "1"
        ids << k.to_i
      end
    end
    self.documents.delete_if { |d| !ids.include?(d.id) }
  end
  
  def prepare_documents(files)
    p = CopyProcess::Processor.new
    self.documents.each do |doc|
      p.parse_each_document(doc.content, files)
    end
    p
  end
  
  def tokens_to_hash(found)
    tokens = {}
    found.each do |f|
      if tokens[f]
        l = tokens[f][1]
        tokens[f] = [f, l + 1]
      else
        tokens[f] = [f, 1]
      end
    end
    tokens
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_filter :authenticate_user!
  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @site }
      format.js { render :layout => false }
      with_parents = params[:parent_structure] == "1"
      encode = params[:html_encode] == "1"
      format.csv { send_data(@site.to_csv(with_parents, encode), :filename => "#{@site.name}.csv", :type => 'text/csv') }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, :notice => 'Site was successfully created.' }
        format.json { render :json => @site, :status => :created, :location => @site }
      else
        format.html { render :action => "new" }
        format.json { render :json => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, :notice => 'Site was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :ok }
    end
  end
  
  def compile_documents
    @site = Site.find(params[:id])
    respond_to do |format|
      @site.compile_to_save(params)
      format.html { redirect_to site_path(@site), :notice => 'Documents compiled' }
    end
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.haml
= form_for(@site) do |f|
  - if @site.errors.any?
    #error_explanation
      %h2= pluralize(@site.errors.count, "error") |
      prohibited this document from being saved:

      %ul
      - @site.errors.full_messages.each do |msg|
        %li= msg

  .field
    = f.label :name 
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit

app/views/sites/_hash.html.haml
- hash.each do |k, v|
  %ul
    %li= "#{v[0]} #{pluralize(v[1], 'time')}"

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th></th>
    <th></th>
  </tr>

<% @sites.each do |site| %>
  <tr>
    <td><%= link_to site.name, site %></td>
    <td><%= site.url %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.haml
%h1 New site

= render 'form'

= link_to 'Back', sites_path

app/views/sites/show.html.haml
%p#notice= notice
- if flash[:error]
  %p#error= flash[:error]

%h1= @site.name

%p
  %b Url:
  = @site.url
  
- if @site.element_types.size > 0
  %p
    = link_to 'View Element Types', site_element_types_path(@site)
    = link_to 'Search/Replace', new_site_search_and_replace_path(@site)


- if @site.documents.size > 0
  %h3 Documents:
  %p
    =button_to "Add Document", new_site_document_path(@site), method: :get, id: 'add_document'
  %table
    %tr
      %th
      %th Edit
      %th Mark for change
      %th Create new version
      %th Delete
    - @site.documents_by_name.each do |k, doc|
      %tr
        %td= check_box_tag "include[#{doc.id}]"
        %td= link_to doc.name, edit_site_document_path(@site, doc.id)
        %td= link_to 'Edit for changes', [@site, doc]
        %td= link_to 'Create new version', document_versions_path(doc.id), method: :post
        %td= link_to "Delete", site_document_path(@site, doc), confirm: 'Are you sure?', method: :delete
      
%p
  =button_to "Add Document", new_site_document_path(@site), method: :get, id: 'add_document'

- if @site.documents.size > 0
  %p Run "Compile Documents" when you wish to input the content into PAGETorrent.
      
  =form_for(@site, :url => compile_documents_path(@site), :html => { method: :post, id: "compile_documents_form" }) do |f|
    %p= f.submit "Compile Documents", :id => 'compile_documents'
    
- if @site.element_types.size > 0
  %h3 Export
  
  =form_for(@site, url: site_path(@site, format: :csv), html: { method: :get }) do |f|
    %p
      = label_tag :parent_structure, "Export with parent types?"
      = check_box_tag :parent_structure, "1", true
    %p
      = label_tag :html_encode, "HTML Encode? (good for french)"
      = check_box_tag :html_encode, "1", false
    %p= f.submit "Export", id: 'export_csv'
      
        
  %h4 Tokens to replace:
  = render :partial => 'hash', :locals => { :hash => @site.tokens }
    
  %h4 Active Tokens:
  = render :partial => 'hash', :locals => { :hash => @site.active_tokens }

= link_to 'Edit', edit_site_path(@site)
= link_to 'Back', sites_path